env:
- CGO_ENABLED=1
release:
  github:
    owner: techierishi
    name: pal
  name_template: '{{.Tag}}'
  replace_existing_draft: true
  mode: append
  skip_upload: false

brews:
  -
    tap:
      owner: techierishi
      name: pal
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    description: "Simple command-line snippet manager"
    homepage: "https://github.com/techierishi/pal"
    install: |
      bin.install Dir['pal']
      zsh_completion.install "misc/completions/zsh/_pal"
    test: |
      system "#{bin}/pal"
builds:
  - id: windows-amd64
    binary: pal-windows-{{ .Arch }}
    main: main.go
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -buildmode=exe
      - -s -w -X 'github.com/techierishi/pal/versioning.Version=v{{ .Version }}'

  # - id: darwin-amd64
  #   main: main.go
  #   binary: pal-darwin-{{ .Arch }}
  #   goos:
  #     - darwin
  #   goarch:
  #     - amd64
  #   env:
  #     - CC=o64-clang
  #     - CXX=o64-clang++
  #   ldflags:
  #     -s -w -X 'github.com/techierishi/pal/versioning.Version=v{{ .Version }}'

  # - id: darwin-arm64
  #   main: main.go
  #   binary: pal-darwin-{{ .Arch }}
  #   goos:
  #     - darwin
  #   goarch:
  #     - arm64
  #   env:
  #     - CC=oa64-clang
  #     - CXX=oa64-clang++
  #   ldflags:
  #     -s -w -X 'github.com/techierishi/pal/versioning.Version=v{{ .Version }}'

  - id: linux-amd64
    main: main.go
    binary: pal-linux-{{ .Arch }}
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=gcc
      - CXX=g++
    ldflags:
      # We need to build a static binary because we are building in a glibc based system and running in a musl container
      -s -w -linkmode external -extldflags "-static" -X 'github.com/techierishi/pal/versioning.Version=v{{ .Version }}'
    tags:
      - netgo
      - osusergo

  - id: linux-arm64
    main: main.go
    binary: pal-linux-{{ .Arch }}
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    ldflags:
      # We need to build a static binary because we are building in a glibc based system and running in a musl container
      -s -w -linkmode external -extldflags "-static" -X 'github.com/techierishi/pal/versioning.Version=v{{ .Version }}'
    tags:
      - netgo
      - osusergo

archives:
  -
    files:
      - LICENSE
      - README.md

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc

# nfpms:
#   -
#     homepage: https://github.com/techierishi/pal
#     maintainer: Rishi <techierishi@gmail.com>
#     description: "Simple command-line snippet manager"
#     bindir: /usr/local/bin
#     license: MIT
#     formats:
#     - deb
#     - rpm

