# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pal < Formula
  desc "Simple command-line snippet manager"
  homepage "https://github.com/techierishi/pal"
  version "0.2.7"
  depends_on :linux

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/techierishi/pal/releases/download/v0.2.7/pal_0.2.7_linux_amd64.tar.gz"
      sha256 "80c902971cbd5c6c60256e0b59027e53056e9f2d160e6d97d6d7ab13ef5c6952"

      def install
        bin.install Dir['pal']
        zsh_completion.install "misc/completions/zsh/_pal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/techierishi/pal/releases/download/v0.2.7/pal_0.2.7_linux_arm64.tar.gz"
      sha256 "522d20e9df43bffb7fa2ce637fbc12c57a885ca2ce528fbf5607d8ffe1854478"

      def install
        bin.install Dir['pal']
        zsh_completion.install "misc/completions/zsh/_pal"
      end
    end
  end

  test do
    system "#{bin}/pal"
  end
end
