name: Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, mac-woind]
    runs-on: ${{ matrix.os }}
    name: Release
    steps:
      - name: Set up Lua
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            # Install Lua on Windows
            choco install lua
          elif [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            # Install Lua on Ubuntu (Linux)
            sudo apt-get update
            sudo apt-get install -y lua5.3
          else
            # Install Lua on MacOS using Homebrew
            brew install lua
          fi
      - name: Display Lua version
        run: lua -v
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5          
        with:
          go-version: '1.22.0-rc.1'
          go-version-file: go.mod
          check-latest: true
      
      - name: Login to GHCR
        uses: docker/login-action@v3  
        with:
          registry: ghcr.io 
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAL_PAT }}

      - name: Generate binary
        run: |
          go version
          go build -ldflags="-s -w" .
          ls

