name: Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install rpm
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Release
        uses: goreleaser/goreleaser-cross@v1.21.5
        with:
          version: v1.22.1
          args: release --rm-dist
          build-args: |
            TAG_VERSION: v1.21
            GORELEASER_VERSION: v1.22.1
        env:
          GITHUB_TOKEN: ${{ secrets.PAL_PAT }}


