name: Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, mac-woind]
    runs-on: ${{ matrix.os }}
    name: Release
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      
      - name: Login to GHCR
        uses: docker/login-action@v3  
        with:
          registry: ghcr.io 
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAL_PAT }}

      - name: Generate binary
        run: |
          go version
          go build .
          ls -lart

