name: Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install rpm
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Run GoReleaser
        run: |
          docker run \
          		--rm \
          		--privileged \
          		-e CGO_ENABLED=1 \
          		-e GITHUB_TOKEN=${GITHUB_TOKEN} \
              -e DOCKER_CONFIG \
          		-v /var/run/docker.sock:/var/run/docker.sock \
          		-v `pwd`:/go/src/$(PACKAGE_NAME) \
          		-w /go/src/$(PACKAGE_NAME) \
          		ghcr.io/goreleaser/goreleaser-cross:${GOLANG_CROSS_VERSION} \
          		--clean --skip-validate
        env:
          PACKAGE_NAME: github.com/techierishi/pal
          GOLANG_CROSS_VERSION: v1.21.6
          GITHUB_TOKEN: ${{ secrets.PAL_PAT }}
          VERSION: ${{ steps.prepare.outputs.tag_name }}


